### ISSUE TITLE
Missing servral funtions

### ISSUE THREAD

**Issue by SinaRozero** [LielXD/xd_doorlock#1]
Can't found these funtions

AddDoorToSystem
DoorSystemSetDoorState
DoorSystemGetDoorState

**Comment by LielXD** [comment]
What do you mean?
It's not functions, it's Natives

**Comment by SinaRozero** [comment]
ah, sorry for forgot to check the native reference.
might be the something wrong I do in the config.lua,
that some player in server tells me the door locks not working and no error prints in client F8.

apologize for my dumb question.
got really tired today.
